### PR TITLE
Fix added void type on decode and encode

### LINKED ISSUE #74: When function return void cause an exception Error (Flutter)
Steps to reproduce:

is a void return
`file.sdkgen`
`fn requestCellPhoneNumberVerification(cellphone: string)`

in `/sdkgen_runtime-1.1.0/lib/http_client.dart` we have:
```
Future<Object> makeRequest(
      String functionName, Map<String, Object> args) async {
...

// in this case func.ret === "void";
return decode(
            typeTable, "$functionName.ret", func.ret, responseBody["result"]);
...
}
```

Object type, do not expect do be "void" in `switch`
`/sdkgen_runtime-1.1.0/lib/types.dart`
```
decode(Map<String, Object> typeTable, String path, Object type, Object value) {
default:
          if (simpleTypes.contains(type)) {
            return simpleEncodeDecode(typeTable, path, type, value);
          } else if (typeTable.containsKey(type)) {
            return decode(typeTable, path, typeTable[type], value);
          } else {
          // Here throw an Exception.
            throw SdkgenTypeException(
                "Unknown type '${jsonEncode(type)}' at '$path'");
          }
}
```

### PR DESCRIPTION
**Pull request by rafaelmpessoa**
Fixes #74

### CODE REVIEW

File: dart-runtime/lib/types.dart [hunk 1]
```diff
@@ -124,6 +124,12 @@ encode(Map<String, Object> typeTable, String path, Object type, Object value) {
               .toUtc()
               .toIso8601String()
               .replaceAll("Z", "");
+        case "void":
+          if (!(value != null)) {
+            throw SdkgenTypeException(
+                "Invalid Type at '$path', expected ${jsonEncode(type)}, got ${jsonEncode(value)}");
+          }
```
Comment (dgadelha) [inline dart-runtime/lib/types.dart:131]: This check is causing a breaking change with other clients, as it doesn't allow an API to change the return type of a method from void to any type. It should be removed :)

File: dart-runtime/lib/types.dart [hunk 2]
```diff
@@ -207,6 +213,12 @@ decode(Map<String, Object> typeTable, String path, Object type, Object value) {
                 "Invalid Type at '$path', expected ${jsonEncode(type)}, got ${jsonEncode(value)}");
           }
           return DateTime.parse("${value}Z").toLocal();
+        case "void":
+          if (!(value != null)) {
+            throw SdkgenTypeException(
+                "Invalid Type at '$path', expected ${jsonEncode(type)}, got ${jsonEncode(value)}");
+          }
```
Comment (dgadelha) [inline dart-runtime/lib/types.dart:220]: Same as before:

This check is causing a breaking change with other clients, as it doesn't allow an API to change the return type of a method from void to any type. It should be removed :)

File: dart-runtime/lib/types.dart (hunk 1 above)
Comment (rafaelmpessoa) [reply dart-runtime/lib/types.dart]: ok, fixed!
